### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by prem2904** [iamskumar/rxcehack#1]
Sir the installation commands😬

**Comment by iamskumar** [comment]
> Sir the installation commands

Hello!! 
Prem -- Hack is not Free 
Contact me on telegram @Prithvihackz

**Comment by EthicalHacker121** [comment]
> Sir the installation commands

Hello, @prem2904 
you can buy from me same hack less price ....
https://t.me/smsn_knt

**Comment by iamskumar** [comment]
Installation command is in the video.
hack is not free,
Kindly connect with me on telegram 
https://t.me/smsn_knt
